# Specify the path to the colmap executable
colmap_exec: colmap
# Crop the image border (x-axis) during undistortion since those regions have more distortion
crop_border: True

# folder where the data is downloaded
data_root: /data1/home/lucky/ELSED/dataset

scene_ids: [3f1e1610de, 67d702f2e8, 69e5939669, 104acbf7d2, 689fec23d7]

# scene_ids: [355e5e32db]

# The max size for colmap undistortion, defining the size of the undistorted image (could be height or width)
max_size: 1440

output_dir: /data1/home/lucky/ELSED/dataset/data_selected
